### PR TITLE
chore: run appveyor on node8 only

### PR DESCRIPTION
**Pull request by alexander-fenster**
We don't run it on node4, 6, 7 for other libraries, no reason to do it in this library as well.

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by callmehiphop** [comment]
Interesting, for some reason I thought we did run it on all major versions? Any reason we don't?

**Comment by alexander-fenster** [comment]
@callmehiphop My understanding is that it's just too slow (we only run 1 build in parallel). Even with just node8 it takes much more time than Circle takes for running tests on all 4 supported versions.

**Comment by alexander-fenster** [comment]
Anyway, the correct action would be either make all libraries run windows builds on all versions, or make this library run windows builds only on node8 - I see no reason of having different setup for different packages :)

**Comment by callmehiphop** [comment]
I totally agree! I was just curious about why we only run 8

**Comment by alexander-fenster** [comment]
As I said, the only reason I can think about is that it's too slow to wait for 4 versions :(
Thanks!

**Pull request merged**
