### PR TITLE
chore: 0.19.0 release proposal

### PR DESCRIPTION
**Pull request by kjin**
[Release Notes](https://github.com/googleapis/nodejs-common/releases/tag/untagged-df9975ca194316f7f3b1)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Have we updated to 0.18.x from any of the client libs? I know Storage is [having issues](https://github.com/googleapis/nodejs-storage/pull/202). Maybe we can do an 0.19-beta until we're officially sorted out, unless you feel going right to 0.19 is best.

**Comment by kjin** [comment]
@stephenplusplus This release can wait. That being said it is only a TS interface change, and to an interface that I am sure no client library is currently using (the `Logger` class, which was introduced in 0.18).

**Comment by JustinBeckwith** [comment]
We have a few other fixes getting log-jammed here.  Given the fact that it's a semver major, and likely won't break clients I'm in favor of cutting a 0.19.0 release.

**Comment by kjin** [comment]
@JustinBeckwith My bad for letting this stagnate. I'll go ahead and add the other changes here?

**Comment by kjin** [comment]
Never mind, looks like you already rebased. Will change the release notes

**Comment by kjin** [comment]
Looks like the new release of `tsc` is breaking things. Will fix this as a separate PR first.

**Comment by JustinBeckwith** [comment]
Rad - merged, and created the release.  @kolodny this should be released in the next few minutes :)

**Pull request merged**
