### PR TITLE
Remove 'is' dependency

### LINKED ISSUE #163: Migrate to @sindresorhus/is
We should use `@sindresorhus/is` instead of just `is`, because it's more consistent.  PR feedback from https://github.com/googleapis/nodejs-common/pull/162

### PR DESCRIPTION
**Pull request by zbjornson**
All of these replacements are synonymous with `is`'s implementations -- all of `is`'s tests pass using these versions.

Closes #163

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by zbjornson** [comment]
Knowing how to check the type of simple, built-in JS values I think is fundamental knowledge. TS is smart enough to know that [`typeof`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards), [`instanceof`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards) and `Array.isArray` narrow the type. I like avoiding dependencies for trivial tasks to make installs fast, keep node_modules small (in this case saving 49 KB), speedup node.js startup, reduce time maintainers have to spend bumping dependencies, and avoid potential upstream bugs and vulnerabilities. (The original `is` library, which is also tiny and popular, has a runtime strict-mode violation that is only not encountered because of another bug in that module, for example.)

That said, obviously not my final decision. 😉

**Comment by JustinBeckwith** [comment]
@carnesen I see where you're coming from, but I like this for a few reasons:
1. The TypeScript compiler can recognize standard typeof guards when evaluating types
2. It's one less dependency in the chain for a very, very foundational library

This is cool to me 👍

**Comment by zbjornson** [comment]
Thanks, both fixed. 🙂 

(@carnesen didn't mean my comment to be rude, sorry if it came off strong.)

**Comment by carnesen** [comment]
@zbjornson No worries at all. I don't mince words either! This is basically just a "leftpad" debate, and I was voicing my vote in favor of the "module" side.

**Pull request merged**
